# Generated by Django 5.1.1 on 2024-10-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='ContactNo',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='readers_id',
        ),
    ]
