# Generated by Django 5.1.1 on 2024-10-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_rename_address_reader_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='reader_id',
            field=models.CharField(default='default_reader_id', max_length=200, unique=True),
        ),
    ]
